import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E8E3FF',
  },
  header: {
    backgroundColor: '#E8E3FF',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 15,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  avatarFallback: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitials: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  avatarBorder: {
    position: 'absolute',
    top: -2,
    left: -2,
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#2D1B69',
  },
  editIconContainer: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#2D1B69',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editIcon: {
    fontSize: 10,
  },
  greetingContainer: {
    flex: 1,
  },
  greeting: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#060070',
    marginBottom: 2,
  },
  dateTime: {
    fontSize: 16,
    color: '#060070',
  },
  streakContainer: {
    alignItems: 'center',
  },
  streakLabel: {
    fontSize: 14,
    color: '#060070',
    marginBottom: 5,
  },
  streakCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#2D1B69',
    justifyContent: 'center',
    alignItems: 'center',
  },
  streakNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#060070',
  },
  statsBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 15,
    backgroundColor: '#F5F3FF',
    marginHorizontal: 20,
    borderRadius: 12,
    marginBottom: 15,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#060070',
  },
  statLabel: {
    fontSize: 12,
    color: '#060070',
    marginTop: 2,
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#E8E3FF',
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    color: '#060070',
    fontWeight: '500',
  },
  medicationCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  medicationCardOverdue: {
    backgroundColor: 'white',
    borderRadius: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  medicationCardContent: {
    padding: 20,
    width: '100%',
  },
  medicationCardContentCompressed: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    width: '100%',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  cardHeaderCompressed: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  categoryText: {
    fontSize: 14,
    color: '#060070',
    fontWeight: '500',
  },
  categoryTextOverdue: {
    fontSize: 14,
    color: '#060070',
    fontWeight: '500',
  },
  overdueNotification: {
    backgroundColor: '#FF6B6B',
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 8,
  },
  missedBadge: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  missedText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  infoButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2D1B69',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoIcon: {
    fontSize: 12,
    color: '#060070',
    fontWeight: 'bold',
  },
  medicationContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  medicationInfo: {
    flex: 1,
  },
  medicationInfoCompressed: {
    flex: 1,
    justifyContent: 'center',
  },
  medicationName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#060070',
    marginBottom: 2,
  },
  medicationNameOverdue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#060070',
    marginBottom: 2,
  },
  medicationNameCompressed: {
    fontSize: 16,
    fontWeight: '500',
    color: '#060070',
    lineHeight: 20,
  },
  genericName: {
    fontSize: 14,
    color: '#060070',
    marginBottom: 5,
  },
  dosageText: {
    fontSize: 14,
    color: '#060070',
    marginBottom: 10,
  },
  timeline: {
    marginTop: 5,
  },
  timelineContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 12,
    marginTop: 4,
  },
  nextDot: {
    backgroundColor: '#6B4E8D',
    marginTop: 8,
  },
  timelineContent: {
    flex: 1,
  },
  statusText: {
    fontSize: 16,
    color: '#060070',
    fontWeight: '500',
    lineHeight: 22,
  },
  statusTextOverdue: {
    fontSize: 16,
    color: '#060070',
    fontWeight: '500',
    lineHeight: 22,
  },
  urgentText: {
    color: '#E74C3C',
  },
  nextIntakeText: {
    fontSize: 16,
    color: '#060070',
    fontWeight: '500',
    marginTop: 8,
    lineHeight: 22,
  },
  statusButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  statusButtonCompressed: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  checkmark: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    width: width * 0.9,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D1B69',
    marginBottom: 20,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    fontSize: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#F0F0F0',
  },
  saveButton: {
    backgroundColor: '#8B5CF6',
  },
  cancelButtonText: {
    color: '#666',
    fontWeight: 'bold',
  },
  saveButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  detailsModal: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    width: width * 0.9,
    maxHeight: '70%',
  },
  detailsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#060070',
    marginBottom: 5,
  },
  detailsSubtitle: {
    fontSize: 16,
    color: '#060070',
    marginBottom: 20,
  },
  detailsContent: {
    marginBottom: 20,
  },
  detailItem: {
    fontSize: 16,
    color: '#060070',
    marginBottom: 10,
    lineHeight: 24,
  },
  closeButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#060070',
    fontWeight: 'bold',
    fontSize: 16,
  },
  bottomButtonsContainer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 40,
    zIndex: 1000,
  },
  sideButton: {
    alignItems: 'center',
  },
  sideButtonLeft: {
    alignItems: 'center',
  },
  sideButtonInner: {
    alignItems: 'center',
  },
  iconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(45, 27, 105, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(45, 27, 105, 0.2)',
  },
  buttonLabel: {
    fontSize: 12,
    color: '#060070',
    fontWeight: '500',
  },
  calendarIcon: {
    width: 18,
    height: 18,
    backgroundColor: '#2D1B69',
    borderRadius: 3,
    position: 'relative',
  },
  wearableIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#2D1B69',
    position: 'relative',
  },
  reportIcon: {
    width: 16,
    height: 20,
    backgroundColor: '#2D1B69',
    borderRadius: 2,
    position: 'relative',
  },
  aiButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'transparent',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
  },
  aiButtonInner: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiButtonGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
    backgroundColor: '#667eea',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 8,
    overflow: 'hidden',
  },
  aiIconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  // Check-in Banner Styles
  checkInBanner: {
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 16,
    backgroundColor: '#E8E3FF',
    shadowColor: '#2D1B69',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  checkInContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  checkInIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    shadowColor: '#2D1B69',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  checkInTextContainer: {
    flex: 1,
  },
  checkInTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D1B69',
    marginBottom: 4,
  },
  checkInSubtitle: {
    fontSize: 14,
    color: '#6B4EFF',
    opacity: 0.8,
  },
}); 