import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E8E3FF',
  },
  header: {
    backgroundColor: '#E8E3FF',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 15,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  avatarFallback: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitials: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  avatarBorder: {
    position: 'absolute',
    top: -2,
    left: -2,
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#2D1B69',
  },
  editIconContainer: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#2D1B69',
    justifyContent: 'center',
    alignItems: 'center',
  },
  editIcon: {
    fontSize: 10,
  },
  greetingContainer: {
    flex: 1,
  },
  greeting: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2D1B69',
    marginBottom: 2,
  },
  dateTime: {
    fontSize: 16,
    color: '#6B4E8D',
  },
  streakContainer: {
    alignItems: 'center',
  },
  streakLabel: {
    fontSize: 14,
    color: '#6B4E8D',
    marginBottom: 5,
  },
  streakCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#2D1B69',
    justifyContent: 'center',
    alignItems: 'center',
  },
  streakNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D1B69',
  },
  statsBar: {
    flexDirection: 'row',
    backgroundColor: 'white',
    marginHorizontal: 20,
    marginBottom: 10,
    borderRadius: 12,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2D1B69',
  },
  statLabel: {
    fontSize: 12,
    color: '#6B4E8D',
    marginTop: 2,
  },
  urgentSection: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  urgentTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E74C3C',
    marginBottom: 10,
  },
  urgentCard: {
    backgroundColor: '#FFF5F5',
    borderRadius: 12,
    padding: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#E74C3C',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  urgentContent: {
    flex: 1,
  },
  urgentMedName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D1B69',
  },
  urgentTime: {
    fontSize: 14,
    color: '#E74C3C',
    fontWeight: '600',
  },
  urgentActions: {
    flexDirection: 'row',
    gap: 10,
  },
  snoozeButton: {
    backgroundColor: '#F0F0F0',
    borderRadius: 20,
    padding: 8,
  },
  snoozeText: {
    fontSize: 16,
  },
  urgentTakeButton: {
    backgroundColor: '#E74C3C',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 8,
  },
  urgentTakeText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#E8E3FF',
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    color: '#2D1B69',
    fontWeight: '500',
  },
  addButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 8,
  },
  addButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  medicationCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  categoryText: {
    fontSize: 14,
    color: '#6B4E8D',
    fontWeight: '500',
  },
  infoButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2D1B69',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoIcon: {
    fontSize: 12,
    color: '#2D1B69',
    fontWeight: 'bold',
  },
  medicationContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  medicationInfo: {
    flex: 1,
  },
  medicationName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2E5BFF',
    marginBottom: 2,
  },
  genericName: {
    fontSize: 14,
    color: '#6B4E8D',
    marginBottom: 5,
  },
  dosageText: {
    fontSize: 14,
    color: '#6B4E8D',
    marginBottom: 10,
  },
  timeline: {
    marginTop: 5,
  },
  timelineContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 12,
    marginTop: 4,
  },
  nextDot: {
    backgroundColor: '#6B4E8D',
    marginTop: 8,
  },
  timelineContent: {
    flex: 1,
  },
  statusText: {
    fontSize: 16,
    color: '#2D1B69',
    fontWeight: '500',
    lineHeight: 22,
  },
  urgentText: {
    color: '#E74C3C',
  },
  nextIntakeText: {
    fontSize: 16,
    color: '#2D1B69',
    fontWeight: '500',
    marginTop: 8,
    lineHeight: 22,
  },
  statusButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  checkmark: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    width: width * 0.9,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D1B69',
    marginBottom: 20,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    fontSize: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#F0F0F0',
  },
  saveButton: {
    backgroundColor: '#8B5CF6',
  },
  cancelButtonText: {
    color: '#666',
    fontWeight: 'bold',
  },
  saveButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  detailsModal: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 25,
    width: width * 0.9,
    maxHeight: '70%',
  },
  detailsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2D1B69',
    marginBottom: 5,
  },
  detailsSubtitle: {
    fontSize: 16,
    color: '#6B4E8D',
    marginBottom: 20,
  },
  detailsContent: {
    marginBottom: 20,
  },
  detailItem: {
    fontSize: 16,
    color: '#2D1B69',
    marginBottom: 10,
    lineHeight: 24,
  },
  closeButton: {
    backgroundColor: '#8B5CF6',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
  },
  closeButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  aiButton: {
    position: 'absolute',
    bottom: 30,
    left: '50%',
    marginLeft: -60,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'transparent',
    shadowColor: '#2D1B69',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
    zIndex: 1000,
  },
  aiButtonInner: {
    width: '100%',
    height: '100%',
    borderRadius: 60,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiButtonGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 60,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 8,
  },
  aiButtonIcon: {
    fontSize: 40,
  },
  reportButton: {
    position: 'absolute',
    bottom: 80,
    right: 30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'transparent',
    shadowColor: '#2D1B69',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  reportButtonInner: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    backgroundColor: '#6B4E8D',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  reportButtonIcon: {
    fontSize: 24,
  },
}); 